# Generated by Django 2.1.1 on 2019-08-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaoyou', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceDetails',
        ),
    ]
