# Generated by Django 2.1.1 on 2019-08-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaoyou', '0002_delete_facedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='手机号')),
                ('time', models.CharField(blank=True, max_length=12, null=True, verbose_name='匹配时间')),
                ('library_picture', models.CharField(blank=True, max_length=255, null=True, verbose_name='脸库图片')),
                ('grap_picture', models.CharField(blank=True, max_length=255, null=True, verbose_name='抓取图片')),
                ('result', models.IntegerField(blank=True, null=True, verbose_name='复查结果')),
            ],
            options={
                'verbose_name_plural': '人脸匹配',
            },
        ),
    ]
