# Generated by Django 2.1.1 on 2019-03-28 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='sendcoupon',
            name='backenduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='后台用户'),
        ),
        migrations.AddField(
            model_name='sendcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.Coupon', verbose_name='优惠券'),
        ),
        migrations.AddField(
            model_name='sendcoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='客户'),
        ),
        migrations.AlterUniqueTogether(
            name='coinrule',
            unique_together={('category', 'company_id')},
        ),
    ]
