# Generated by Django 2.1.1 on 2019-03-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('discount', '0001_initial'),
        ('sale', '0002_auto_20190324_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='sendcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.Coupon', verbose_name='优惠券'),
        ),
        migrations.AddField(
            model_name='sendcoupon',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Seller', verbose_name='销售'),
        ),
        migrations.AddField(
            model_name='sendcoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='客户'),
        ),
        migrations.AlterUniqueTogether(
            name='coinrule',
            unique_together={('category', 'store_code')},
        ),
    ]
