# Generated by Django 2.1.1 on 2019-03-22 08:43

import crm.user.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190322_1014'),
        ('discount', '0002_auto_20190322_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoinRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('coin', models.IntegerField(default=0, verbose_name='赠送积分')),
                ('update_status', models.BooleanField(default=False, verbose_name='更新状态')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.CoinRule', verbose_name='类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户积分记录',
            },
            bases=(models.Model, crm.user.models.UserMobileMixin),
        ),
    ]
