# Generated by Django 2.1.1 on 2019-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20190328_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinQRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='qrcode编码')),
                ('qr_code_url', models.URLField(max_length=500, verbose_name='二维码图片链接')),
            ],
            options={
                'verbose_name_plural': '积分二维码',
                'verbose_name': '积分二维码',
            },
        ),
    ]
