# Generated by Django 2.1.1 on 2019-03-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20190326_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinrule',
            name='category',
            field=models.IntegerField(choices=[(0, '注册送积分'), (1, '到访送积分'), (2, '问卷积分'), (3, '3D看房送积分'), (4, '签到送积分'), (5, '看样板房送积分'), (6, '活动扫码送积分1'), (7, '活动扫码送积分2'), (8, '活动扫码送积分3'), (9, '活动扫码送积分4'), (10, '活动扫码送积分5')], verbose_name='积分规则'),
        ),
    ]
