# Generated by Django 2.1.1 on 2019-03-25 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_coupon_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcoupon',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='后台用户'),
        ),
    ]
