# Generated by Django 2.1.1 on 2019-03-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20190327_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinrecord',
            name='extra_data',
            field=models.TextField(default='', verbose_name='额外参数'),
        ),
        migrations.AlterField(
            model_name='usercoinrecord',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discount.CoinRule', verbose_name='类型'),
        ),
    ]
