# Generated by Django 2.1.1 on 2019-03-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20190325_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendcoupon',
            old_name='seller',
            new_name='backenduser',
        ),
    ]
