# Generated by Django 2.1.1 on 2019-03-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_auto_20190328_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinrule',
            name='company_id',
            field=models.CharField(max_length=255, verbose_name='公司编码'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='company_id',
            field=models.CharField(max_length=255, verbose_name='公司编码'),
        ),
    ]
