# Generated by Django 2.1.1 on 2019-07-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_auto_20190507_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinqrcode',
            name='code',
            field=models.CharField(max_length=50, verbose_name='qrcode编码'),
        ),
        migrations.AlterUniqueTogether(
            name='coinqrcode',
            unique_together={('code', 'company_id')},
        ),
    ]
