# Generated by Django 2.1.1 on 2019-04-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_auto_20190404_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinrule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
