# Generated by Django 2.1.1 on 2019-04-11 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_auto_20190411_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinrule',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
