# Generated by Django 2.1.1 on 2019-04-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0010_auto_20190411_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinrule',
            name='category',
            field=models.IntegerField(choices=[(0, '注册送积分'), (1, '到访送积分'), (3, '3D看房送积分'), (5, '看样板房送积分'), (6, '绑定销售'), (7, '门店到访'), (8, '活动扫码送积分三'), (9, '活动扫码送积分四'), (10, '活动扫码送积分五')], verbose_name='积分规则'),
        ),
    ]
