# Generated by Django 2.1.1 on 2019-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0011_auto_20190412_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinrule',
            name='category',
            field=models.IntegerField(choices=[(0, '注册送积分'), (2, '完善个人信息'), (3, '3D看房送积分'), (5, '看样板房送积分'), (8, '活动扫码送积分一'), (9, '活动扫码送积分二'), (10, '活动扫码送积分三')], verbose_name='积分规则'),
        ),
    ]
