# Generated by Django 2.1.1 on 2019-04-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0012_auto_20190415_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoinrecord',
            name='extra_data',
            field=models.TextField(default='{}', verbose_name='额外参数'),
        ),
    ]
