# Generated by Django 2.1.1 on 2019-04-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0014_pointrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='return_order_no',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='user',
        ),
    ]
