# Generated by Django 2.1.1 on 2019-04-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190415_1453'),
        ('discount', '0015_auto_20190416_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrecord',
            name='coin',
            field=models.IntegerField(default=0, verbose_name='积分变更值'),
        ),
        migrations.AddField(
            model_name='pointrecord',
            name='order_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='订单编号'),
        ),
        migrations.AddField(
            model_name='pointrecord',
            name='return_order_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='退单编号'),
        ),
        migrations.AddField(
            model_name='pointrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='用户'),
            preserve_default=False,
        ),
    ]
