# Generated by Django 2.1.1 on 2019-04-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20190411_2014'),
        ('discount', '0017_auto_20190416_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrecord',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.Seller', verbose_name='销售'),
        ),
    ]
