# Generated by Django 2.1.1 on 2019-04-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0018_pointrecord_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrecord',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.CoinRule', verbose_name='积分规则'),
        ),
    ]
