# Generated by Django 2.1.1 on 2019-04-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0019_pointrecord_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoinrecord',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='usercoinrecord',
            name='user',
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='change_type',
            field=models.CharField(choices=[('order', '订单'), ('return_order', '退单'), ('seller_send', '积分赠予'), ('rule_reward', '积分奖励')], default='order', max_length=20, verbose_name='变更类型'),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.BaseUser', verbose_name='后台管理'),
        ),
        migrations.DeleteModel(
            name='UserCoinRecord',
        ),
    ]
