# Generated by Django 2.1.1 on 2019-04-16 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0020_auto_20190416_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointrecord',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='后台管理'),
        ),
    ]
