# Generated by Django 2.1.1 on 2019-03-20 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户关系',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.BaseUser', verbose_name='用户')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('code', models.CharField(max_length=50, verbose_name='qrcode编码')),
                ('qr_code_url', models.CharField(max_length=500, verbose_name='二维码图片链接')),
            ],
            options={
                'verbose_name': '销售人员',
            },
        ),
        migrations.AddField(
            model_name='customerrelation',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Seller', verbose_name='销售'),
        ),
        migrations.AddField(
            model_name='customerrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='客户'),
        ),
    ]
