# Generated by Django 2.1.1 on 2019-03-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrelation',
            name='mark_name',
            field=models.CharField(default='', max_length=25, verbose_name='备注昵称'),
        ),
    ]
