# Generated by Django 2.1.1 on 2019-03-28 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='qrcode编码')),
                ('qr_code_url', models.URLField(max_length=500, verbose_name='二维码图片链接')),
            ],
            options={
                'verbose_name': '二维码',
                'verbose_name_plural': '二维码',
            },
        ),
        migrations.RemoveField(
            model_name='seller',
            name='code',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='qr_code_url',
        ),
        migrations.AddField(
            model_name='seller',
            name='qrcode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='sale.QRCode', verbose_name='二维码'),
        ),
    ]
