# Generated by Django 2.1.1 on 2019-07-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(max_length=50, verbose_name='qrcode编码'),
        ),
        migrations.AlterUniqueTogether(
            name='qrcode',
            unique_together={('code', 'company_id')},
        ),
    ]
