# Generated by Django 2.1.1 on 2019-03-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20190328_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'verbose_name': '销售二维码', 'verbose_name_plural': '销售二维码'},
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='qrcode编码'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='qrcode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='sale.QRCode', verbose_name='二维码'),
        ),
    ]
