# Generated by Django 2.1.1 on 2019-07-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20190705_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='头像链接'),
        ),
        migrations.AddField(
            model_name='seller',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职业'),
        ),
    ]
