# Generated by Django 2.1.1 on 2019-03-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20190324_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrelation',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
