# Generated by Django 2.1.1 on 2019-03-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20190328_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='company_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='公司id'),
        ),
    ]
