# Generated by Django 2.1.1 on 2019-03-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('sale', '0003_customerrelation_is_delete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerrelation',
            unique_together={('seller', 'user')},
        ),
    ]
