# Generated by Django 2.1.1 on 2019-03-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_qrcode_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
    ]
