# Generated by Django 2.1.1 on 2019-07-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='profession',
        ),
    ]
