# Generated by Django 2.1.1 on 2019-04-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_remove_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrelation',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
