# Generated by Django 2.1.1 on 2019-04-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20190402_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrelation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
