# Generated by Django 2.1.1 on 2019-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mobile', models.CharField(max_length=100, verbose_name='用户手机号')),
                ('sample_room_times', models.IntegerField(default=0, verbose_name='当天看样板房次数')),
                ('sample_room_seconds', models.IntegerField(default=0, verbose_name='当天看样板房时间(s)')),
                ('big_room_seconds', models.IntegerField(default=0, verbose_name='当天售楼大厅停留时间(s)')),
                ('store_seconds', models.IntegerField(default=0, verbose_name='当天小店停留时间(s)')),
                ('spend_coin', models.IntegerField(default=0, verbose_name='当天消费积分')),
                ('vr_times', models.IntegerField(default=0, verbose_name='当天VR看房次数')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='创建于')),
            ],
            options={
                'verbose_name_plural': '每日统计数据',
                'verbose_name': '每日统计数据',
            },
        ),
    ]
