# Generated by Django 2.1.1 on 2019-04-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisReport',
        ),
    ]
