# Generated by Django 2.1.1 on 2019-03-20 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=25, verbose_name='用户手机号')),
                ('store_code', models.CharField(max_length=255, verbose_name='门店编码')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('category', models.IntegerField(choices=[(0, '男')], default=0, verbose_name='类别')),
                ('location', models.CharField(max_length=50, verbose_name='位置')),
            ],
            options={
                'verbose_name': '用户行为',
            },
        ),
        migrations.CreateModel(
            name='UserOnlineOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('location', models.CharField(max_length=50, verbose_name='点餐位置')),
                ('detail', models.TextField(default='', verbose_name='点餐详情')),
            ],
            options={
                'verbose_name': '用户在线点餐',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.BaseUser', verbose_name='用户')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=25, verbose_name='用户昵称')),
                ('age', models.IntegerField(default=-1, verbose_name='年龄')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('status', models.IntegerField(choices=[(0, '接触中'), (1, '观望中'), (2, '购房成功')], default=0, verbose_name='购房状态')),
                ('note', models.TextField(default='', verbose_name='备注')),
                ('willingness', models.CharField(default='', max_length=5, verbose_name='意愿度')),
                ('net_worth', models.CharField(default='', max_length=5, verbose_name='净值度')),
            ],
            options={
                'verbose_name': '用户基本信息',
            },
        ),
        migrations.AddField(
            model_name='useronlineorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.BaseUser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.BaseUser', verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='baseuser',
            unique_together={('mobile', 'store_code')},
        ),
    ]
