# Generated by Django 2.1.1 on 2019-03-26 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='access_times',
            field=models.IntegerField(default=0, verbose_name='到访次数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='extra_data',
            field=models.TextField(default='', verbose_name='额外参数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_active_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='活跃时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='spend_coin',
            field=models.IntegerField(default=0, verbose_name='花费积分'),
        ),
    ]
