# Generated by Django 2.1.1 on 2019-03-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendrole',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='是否销售'),
        ),
        migrations.AddField(
            model_name='backenduser',
            name='name',
            field=models.CharField(default='', max_length=25, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='backendrole',
            name='only_myself',
            field=models.BooleanField(default=False, verbose_name='查看自己数据'),
        ),
    ]
