# Generated by Django 2.1.1 on 2019-03-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendrole',
            name='store_code',
            field=models.CharField(default='c0001', max_length=255, verbose_name='门店编码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backenduser',
            name='store_code',
            field=models.CharField(max_length=255, verbose_name='门店编码'),
        ),
    ]
