# Generated by Django 2.1.1 on 2019-03-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior',
            name='category',
            field=models.CharField(max_length=20, verbose_name='类别'),
        ),
    ]
