# Generated by Django 2.1.1 on 2019-04-04 03:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190329_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='extra_data',
            field=jsonfield.fields.JSONField(default={}, verbose_name='额外参数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '未接触'), (1, '观望中'), (2, '购房成功'), (3, '接触中')], default=0, verbose_name='购房状态'),
        ),
    ]
