# Generated by Django 2.1.1 on 2019-03-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190325_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.CharField(default='', max_length=25, verbose_name='年龄'),
        ),
    ]
