# Generated by Django 2.1.1 on 2019-03-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190327_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='coin',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
