# Generated by Django 2.1.1 on 2019-04-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_staytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_total', models.IntegerField(verbose_name='来访人数')),
                ('register_total', models.IntegerField(verbose_name='注册人数')),
                ('sample_room_total', models.IntegerField(verbose_name='样板房参观人数')),
                ('micro_store_total', models.IntegerField(verbose_name='小店参数人数')),
                ('created_at', models.DateField(verbose_name='创建于')),
            ],
            options={
                'verbose_name_plural': '参观数据',
                'verbose_name': '参观数据',
            },
        ),
    ]
