# Generated by Django 2.1.1 on 2019-04-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190404_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
    ]
