# Generated by Django 2.1.1 on 2019-04-08 09:17

import crm.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190404_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='msg_last_at',
            field=models.DateTimeField(default=crm.user.models.before_day, verbose_name='上次读取消息时间'),
        ),
    ]
