# Generated by Django 2.1.1 on 2019-04-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinfo_msg_last_at'),
        ('user', '0005_auto_20190408_2042'),
    ]

    operations = [
    ]
