# Generated by Django 2.1.1 on 2019-04-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20190410_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='extra_data',
            field=models.TextField(default='{}', verbose_name='额外参数'),
        ),
    ]
