# Generated by Django 2.1.1 on 2019-04-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190426_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_active_time',
            field=models.DateTimeField(verbose_name='活跃时间'),
        ),
    ]
