# Generated by Django 2.1.1 on 2019-04-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190410_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_access_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近到访时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sampleroom_seconds',
            field=models.IntegerField(default=0, verbose_name='看样板房总停留秒数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sampleroom_times',
            field=models.IntegerField(default=0, verbose_name='看样板房次数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sdver_times',
            field=models.IntegerField(default=0, verbose_name='3DVR看房次数'),
        ),
    ]
