# Generated by Django 2.1.1 on 2019-04-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190411_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='last_access_at',
        ),
    ]
