# Generated by Django 2.1.1 on 2019-04-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_userinfo_last_access_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
