# Generated by Django 2.1.1 on 2019-05-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190428_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='是否为员工'),
        ),
    ]
