# Generated by Django 2.1.1 on 2019-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190411_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='industry',
            field=models.IntegerField(choices=[(0, '其他'), (1, '政府机关'), (2, '事业单位'), (3, '建筑建材'), (4, '金融投资'), (5, '外贸'), (6, '消费零售'), (7, '制造行业'), (8, '广告传媒'), (9, '医药行业'), (10, '交通运输'), (11, 'IT及互联网'), (12, '教育行业'), (13, '退休'), (14, '商业服务')], default=0, verbose_name='工作行业'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='product_intention',
            field=models.CharField(default='', max_length=50, verbose_name='意向产品'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='purchase_purpose',
            field=models.CharField(default='', max_length=50, verbose_name='购买用途'),
        ),
    ]
