# Generated by Django 2.1.1 on 2019-05-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_userinfo_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tags',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='标签'),
        ),
    ]
