# Generated by Django 2.1.1 on 2019-04-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190417_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='big_room_seconds',
            field=models.IntegerField(default=0, verbose_name='大厅总停留时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='microstore_seconds',
            field=models.IntegerField(default=0, verbose_name='小店总停留秒数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='microstore_times',
            field=models.IntegerField(default=0, verbose_name='小店次数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='self_willingness',
            field=models.CharField(choices=[('1', '低'), ('2', '中'), ('3', '高'), ('4', '极高')], default='1', max_length=5, verbose_name='主观意愿度'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='willingness',
            field=models.CharField(choices=[('1', '低'), ('2', '中'), ('3', '高'), ('4', '极高')], default='1', max_length=5, verbose_name='客观意愿度'),
        ),
    ]
