# Generated by Django 2.1.1 on 2019-04-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190417_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
    ]
