# Generated by Django 2.1.1 on 2019-05-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190522_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdailydata',
            options={'verbose_name': '没人每天统计数据', 'verbose_name_plural': '没人每天统计数据'},
        ),
    ]
