# Generated by Django 2.1.1 on 2019-06-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190522_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_host', models.CharField(max_length=20, verbose_name='域名')),
                ('config', models.TextField(verbose_name='配置json')),
            ],
            options={
                'verbose_name': '后台配置',
                'verbose_name_plural': '后台配置',
            },
        ),
    ]
