# Generated by Django 2.1.1 on 2019-06-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20190621_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='buy_done',
            field=models.BooleanField(default=False, verbose_name='是否成交'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='introducer_mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='介绍人手机号码'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='introducer_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='介绍人姓名'),
        ),
    ]
