# Generated by Django 2.1.1 on 2019-07-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190628_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='company_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='公司id'),
        ),
    ]
