# Generated by Django 2.1.1 on 2019-07-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20190703_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backenduser',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='backenduser',
            name='username',
            field=models.CharField(max_length=30, verbose_name='用户名'),
        ),
        migrations.AlterUniqueTogether(
            name='backenduser',
            unique_together={('username', 'company_id'), ('mobile', 'company_id')},
        ),
    ]
