# Generated by Django 2.1.1 on 2019-07-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20190703_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteconfig',
            name='company_id',
            field=models.CharField(max_length=20, null=True, verbose_name='公司id'),
        ),
    ]
