# Generated by Django 2.1.1 on 2019-07-15 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20190705_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('序号', models.IntegerField(default=0)),
                ('标题名', models.CharField(max_length=200)),
                ('是否单选', models.BooleanField()),
                ('company_id', models.CharField(max_length=20, null=True, verbose_name='公司id')),
            ],
            options={
                'verbose_name': '意向购买问题',
                'verbose_name_plural': '意向购买问题',
            },
        ),
        migrations.CreateModel(
            name='SubTitleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('选项内容', models.CharField(max_length=200)),
                ('意向购买问题', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SubTitle')),
            ],
            options={
                'verbose_name': '意向购买选项',
                'verbose_name_plural': '意向购买选项',
            },
        ),
        migrations.CreateModel(
            name='SubTitleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('是否单选', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.BaseUser', verbose_name='用户')),
                ('意向购买问题', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SubTitleChoice')),
            ],
            options={
                'verbose_name': '意向记录',
                'verbose_name_plural': '意向记录',
            },
        ),
    ]
