# Generated by Django 2.1.1 on 2019-08-23 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20190705_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior',
            name='face_image_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='捕捉图像'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='lib_image_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='脸库图像'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='result',
            field=models.IntegerField(choices=[(0, '未勾选'), (1, '正确'), (2, '错误')], default=0, verbose_name='复查结果'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.BaseUser', verbose_name='用户(外键)'),
        ),
    ]
