# Generated by Django 2.1.1 on 2019-07-15 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_subtitle_subtitlechoice_subtitlerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='序号',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='是否单选',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='标题名',
        ),
        migrations.RemoveField(
            model_name='subtitlechoice',
            name='意向购买问题',
        ),
        migrations.RemoveField(
            model_name='subtitlechoice',
            name='选项内容',
        ),
        migrations.RemoveField(
            model_name='subtitlerecord',
            name='意向购买问题',
        ),
        migrations.RemoveField(
            model_name='subtitlerecord',
            name='是否单选',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='is_single',
            field=models.BooleanField(default=True, verbose_name='是否单选'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标题名'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='no',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='subtitlechoice',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='选项内容'),
        ),
        migrations.AddField(
            model_name='subtitlechoice',
            name='sub_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.SubTitle', verbose_name='意向购买问题'),
        ),
        migrations.AddField(
            model_name='subtitlerecord',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.SubTitleChoice', verbose_name='意向购买问题'),
        ),
        migrations.AddField(
            model_name='subtitlerecord',
            name='is_choose',
            field=models.BooleanField(default=True, verbose_name='是否'),
        ),
    ]
