# Generated by Django 2.1.1 on 2019-07-15 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20190715_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitlerecord',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='subtitlerecord',
            name='is_choose',
        ),
        migrations.AddField(
            model_name='subtitlerecord',
            name='choice_choose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.SubTitleChoice', verbose_name='意向购买问题答案'),
        ),
        migrations.AddField(
            model_name='subtitlerecord',
            name='sub_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.SubTitle', verbose_name='意向购买问题'),
        ),
    ]
