# Generated by Django 2.1.1 on 2019-07-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20190715_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitlerecord',
            name='choice_choose',
        ),
        migrations.AddField(
            model_name='subtitlerecord',
            name='choice_choose',
            field=models.ManyToManyField(to='user.SubTitleChoice', verbose_name='意向购买问题答案'),
        ),
    ]
