# Generated by Django 2.1.1 on 2019-07-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20190718_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='头像链接'),
        ),
    ]
