# Generated by Django 2.1.1 on 2019-07-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_record', to='user.BaseUser', verbose_name='专属销售'),
        ),
    ]
