# Generated by Django 2.1.1 on 2019-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_userbehavior_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbehavior',
            name='seller',
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='seller_mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='销售手机号'),
        ),
    ]
