# Generated by Django 2.1.1 on 2019-07-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20190725_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbehavior',
            name='seller_mobile',
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='visited_mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='被访人手机号'),
        ),
    ]
