# Generated by Django 2.1.1 on 2019-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20190725_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='area_of_house',
            field=models.CharField(blank=True, choices=[('1', '100-110m2'), ('2', '110-120m2'), ('3', '120-130m2'), ('4', '130-140m2'), ('5', '140m2以上')], max_length=5, null=True, verbose_name='面积需求'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='budget_of_house',
            field=models.CharField(blank=True, choices=[('1', '80万以下'), ('2', '80-90万'), ('3', '91-100万'), ('4', '101-110万'), ('5', '111-120万'), ('6', '120万以上')], max_length=5, null=True, verbose_name='预算'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='community',
            field=models.CharField(blank=True, choices=[('1', '龙蟠里'), ('2', '虎踞湾')], max_length=5, null=True, verbose_name='选择小区'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='have_discretion',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否为买房决策人?'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='target_of_buy_house',
            field=models.CharField(blank=True, choices=[('1', '常驻'), ('2', '改善'), ('3', '投资'), ('4', '养老'), ('5', '其他')], max_length=5, null=True, verbose_name='购房目的'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='times_of_buy',
            field=models.CharField(blank=True, choices=[('1', '首次置业'), ('2', '二次置业'), ('3', '三次置业'), ('4', '四次置业及以上')], max_length=5, null=True, verbose_name='置业次数'),
        ),
    ]
