# Generated by Django 2.1.1 on 2019-07-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20190725_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='have_discretion',
            field=models.BooleanField(default=False, verbose_name='是否为买房决策人?'),
        ),
    ]
