# Generated by Django 2.1.1 on 2019-07-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20190725_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='target_of_buy_house',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='购房目的'),
        ),
    ]
