# Generated by Django 2.1.1 on 2019-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20190726_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='backenduser',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='头像链接'),
        ),
    ]
