# Generated by Django 2.1.1 on 2019-08-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_backenduser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='buy_count',
            field=models.PositiveIntegerField(default=0, verbose_name='成交套数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='referrer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='介绍人'),
        ),
    ]
