# Generated by Django 2.1.1 on 2019-08-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20190808_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='called_times',
            field=models.PositiveIntegerField(default=0, verbose_name='被访问次数'),
        ),
    ]
