# Generated by Django 2.1.1 on 2019-08-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_userinfo_called_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='VR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=20, null=True, verbose_name='公司id')),
                ('left', models.URLField(verbose_name='左')),
                ('right', models.URLField(verbose_name='右')),
            ],
            options={
                'verbose_name': 'VR链接',
                'verbose_name_plural': 'VR链接',
            },
        ),
    ]
